### ISSUE TITLE
publish module

### ISSUE THREAD

**Issue by 3052** [zishuzy/m3u8-downloader#2]
change to `github.com/zishuzy/m3u8-downloader`

https://github.com/zishuzy/m3u8-downloader/blob/1b5b0b7ed52ef9f37e60c7751b83d0c2e4b6fcdd/go.mod#L1

**Comment by zishuzy** [comment]
Thanks again. I am a beginner. I've changed the module name. zishuzy/m3u8-downloader@a7e11a8
